### ISSUE TITLE
Just a question, not an issue

### ISSUE THREAD

**Issue by graemeg** [CWBudde/AggPasMod#4]
You stated in the README file 

> Initially I started the port only to see how it compares performance wise.

So what was the conclusion of that?  Is using Class types faster than Object types?

I use the original AggPas code for some years, and have been wondering the same thing - if porting it to Class style objects would made any performance difference. Seems you might have found the results for me. :+1: 

How did you test the performance difference before and after?

**Comment by CWBudde** [comment]
I wanted to compare the performance of the (different) AggPas vector engine(s) with the "VPR" vector engine of GR32.

In addition I wanted to see why the AggPas was different and why. Since I wasn't sure about the optimization tricks for objects I wanted it to be a rather fair comparison which is why I converted it to classes.

As can be guessed it turned out to be a comparison of apples and oranges. This said, it lead to a new vector engine for GR32 which is based on AggPas code (which itself was inspired by early FreeType code).
